# Generated by Django 5.2.4 on 2025-08-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_status_order_paypal_payer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Paiement en ligne'), ('cash_on_delivery', 'Paiement à la livraison')], default='cash_on_delivery', max_length=20),
        ),
    ]
